// svelte/src/lib/Glyphon.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	export let mode: 'onmount' | 'onhover' = 'onhover';
	export let text: string;
	export let alphabet: string = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
	export let as: string = 'span';
	export let id: string = `glyphon-effect-${text}`;
	const defaultOptions = {
		iterationsPerGlyph: 3,
		speed: 30,
		glyphs: alphabet
	};
	export let options = defaultOptions;

	const {
		glyphs = defaultOptions.glyphs,
		iterationsPerGlyph = defaultOptions.iterationsPerGlyph,
		speed = defaultOptions.speed
	} = options;

	const randomLetter = (alphabet: string[]) =>
		alphabet[Math.floor(Math.random() * alphabet.length)];

	let hasEffectFinished = true;

	let finalAlphabet: string[] = [...new Set(glyphs)];

	let result = text;

	let interval: NodeJS.Timer;
	let intervals: NodeJS.Timer[] = [];
	let iteration = 0;

	const onFinishEffect = () => {
		hasEffectFinished = true;
		intervals.forEach((interval) => clearInterval(interval));
	};

	const onMouseOverEffect = () => {
		if (!hasEffectFinished) return;
		iteration = 0;
		hasEffectFinished = false;

		clearInterval(interval);

		interval = setInterval(() => {
			result = text
				.split('')
				.map((_, index) => {
					if (index < iteration) {
						if (text[index] === ' ') return ' ';
						return text[index];
					}

					return randomLetter(finalAlphabet);
				})
				.join('');

			if (iteration >= text.length) {
				onFinishEffect();
			}

			iteration += 1 / iterationsPerGlyph;
		}, speed);

		intervals.push(interval);
	};

	const onMountEffect = () => {
		if (!hasEffectFinished) return;
		iteration = 0;
		interval = setInterval(() => {
			result = text
				.split('')
				.map((_, index) => {
					if (index < iteration) {
						if (text[index] === ' ') return ' ';
						return text[index];
					}
					return randomLetter(finalAlphabet);
				})
				.join('');

			if (iteration >= text.length) {
				onFinishEffect();
			}
			iteration += 1 / iterationsPerGlyph;
		}, speed);
		intervals.push(interval);
	};
	onMount(() => {
		const element = document.getElementById(id);
		if (!element) return;

		if (mode === 'onhover') {
			element.onmouseover = onMouseOverEffect;
		}
		if (mode === 'onmount') {
			element.onmouseover = onMountEffect;
		}
	});
</script>

<svelte:element this={as} {id}>{result}</svelte:element>

// react/src/Glyphon.tsx
import { useEffect, useState, useRef } from "react";

export const defaultAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

type Options = {
    iterationsPerGlyph?: number;
    speed?: number;
    glyphs?: string;
}
type Props = {
    id?: string;
    options?: Options;
    alphabet?: string;
    mode?: 'onhover' | 'onmount'
    text: string;
    [key: string]: unknown;
}

const defaultOptions = {
    iterationsPerGlyph: 3,
    speed: 50,
    glyphs: defaultAlphabet
}

const randomLetter = (alphabet: string[]) => alphabet[Math.floor(Math.random() * alphabet.length)];

export const Glyphon = ({ id, options = defaultOptions, mode = 'onhover', text, ...rest }: Props) => {
    const { glyphs = defaultOptions.glyphs, iterationsPerGlyph = defaultOptions.iterationsPerGlyph, speed = defaultOptions.speed } = options
    const interval = useRef<NodeJS.Timer>();
    const intervals = useRef<NodeJS.Timer[]>([]);

    const hasFinished = useRef(true);
    const iteration = useRef(0);
    const finalAlphabet = [...new Set(glyphs)];

    const [result, setResult] = useState<string>(text);

    const onHoverEffect = () => {
        if (!hasFinished.current) return
        iteration.current = 0;
        hasFinished.current = false

        interval.current = setInterval(() => {
            setResult(result =>
                result.split("").map((_, index) => {
                    if (index < iteration.current) {
                        if (text[index] === ' ') return ' '
                        return text[index];
                    }
                    return randomLetter(finalAlphabet)
                }).join("")
            );

            if (iteration.current >= text.length) {
                onFinishEffect()
            }
            iteration.current += 1 / iterationsPerGlyph;

        }, speed);
        intervals.current.push(interval.current)
    }

    const onMountEffect = () => {
        if (!hasFinished.current) return
        iteration.current = 0;
        interval.current = setInterval(() => {
            setResult(result =>
                result.split("").map((_, index) => {
                    if (index < iteration.current) {
                        if (text[index] === ' ') return ' '
                        return text[index];
                    }
                    return randomLetter(finalAlphabet)
                }).join("")
            )

            if (iteration.current >= text.length) {
                onFinishEffect()
            }
            iteration.current += 1 / iterationsPerGlyph;


        }, speed);
        intervals.current.push(interval.current)
    }

    const onFinishEffect = () => {
        hasFinished.current = true;
        intervals.current.forEach(interval => clearInterval(interval))
    }

    useEffect(() => {
        const el = document?.getElementById?.(id || `glyph-effect-${text}`);
        if (!el) return;

        if (mode === 'onhover') {
            el.onmouseover = onHoverEffect
        }
        if (mode === 'onmount') {
            el.onmouseover = onMountEffect
        }
    })

    return (
        <span id={id || `glyph-effect-${text}`} {...rest}>
            {result}
        </span>
    )
}
